# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='defaultValue',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attribute',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
