# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20160511_0011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': (('export_csv', 'Can Export CSV'), ('send_email', 'Can Send via Email'))},
        ),
    ]
