# Generated by Django 2.0 on 2018-04-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neplist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cron',
            name='day_of_month',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='cron',
            name='day_of_week',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='cron',
            name='hour',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='cron',
            name='minute',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='cron',
            name='month',
            field=models.CharField(max_length=64),
        ),
    ]
