# Generated by Django 2.0 on 2018-04-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neplist', '0003_auto_20180414_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checktemplate',
            name='lists',
            field=models.ManyToManyField(to='neplist.CheckListTemplate'),
        ),
    ]
