# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nepcore', '0002_auto_20160512_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nepuser',
            name='nepPermissions',
        ),
        migrations.RemoveField(
            model_name='nepuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='NEPPermission',
        ),
        migrations.DeleteModel(
            name='NEPUser',
        ),
    ]
