# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nepcore', '0003_auto_20160512_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='NEPPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': ('test_perm', 'Test Permission'),
            },
        ),
    ]
