# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nepcore', '0004_neppermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neppermission',
            options={'permissions': (('test_perm', 'Test Permission'),)},
        ),
    ]
