# Generated by Django 2.0 on 2017-12-31 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nepcore', '0007_nepsiteconfig_default_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='NEPMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='menu_icons')),
                ('state', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=150)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', related_query_name='menu', to='nepcore.NEPMenu')),
            ],
        ),
    ]
