# Generated by Django 2.0 on 2017-12-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepcore', '0008_nepmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nepmenu',
            name='icon',
            field=models.CharField(max_length=50),
        ),
    ]
