# Generated by Django 2.0 on 2017-12-31 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nepcore', '0010_auto_20171231_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='NEPState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=150)),
                ('params', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='nepmenu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', related_query_name='menu', to='nepcore.NEPMenu'),
        ),
        migrations.AlterField(
            model_name='nepmenu',
            name='state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='nepcore.NEPState'),
            preserve_default=False,
        ),
    ]
