# Generated by Django 2.0 on 2017-12-31 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nepcore', '0011_auto_20171231_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nepmenu',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nepcore.NEPState'),
        ),
        migrations.AlterField(
            model_name='nepmenu',
            name='text',
            field=models.CharField(default='DEFAULTED_BY_MIGRATION', max_length=100),
            preserve_default=False,
        ),
    ]
