# Generated by Django 2.0 on 2018-04-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepcore', '0013_auto_20171231_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nepmenu',
            options={'verbose_name': 'Menu'},
        ),
        migrations.AlterModelOptions(
            name='nepstate',
            options={'verbose_name': 'State'},
        ),
        migrations.AlterField(
            model_name='nepsiteconfig',
            name='default_view',
            field=models.CharField(default='nep_index', max_length=255),
        ),
    ]
